package com.umain.sentry.data.repository

import com.umain.sentry.data.model.ActivityEvent
import com.umain.sentry.data.model.ActivityKind
import com.umain.sentry.data.model.CurtainPosition
import com.umain.sentry.data.model.Device
import com.umain.sentry.data.model.DeviceState
import com.umain.sentry.data.model.Room
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import org.koin.core.annotation.Single

/**
 * In-memory fake repository, seeded with the devices and activity events
 * visible in the Phenomenon Studio mockup. Exposed as a Koin `@Single` bound
 * to the [SmartHomeRepository] interface — wiring is generated by the Koin
 * compiler plugin.
 */
@Single(binds = [SmartHomeRepository::class])
class SmartHomeRepositoryImpl : SmartHomeRepository {

    override val homeName: String = "Sia's home"
    override val homeOwnerFirstName: String = "Sia"

    private val _rooms = MutableStateFlow(seedRooms())
    override val rooms: StateFlow<List<Room>> = _rooms.asStateFlow()

    private val _devices = MutableStateFlow(seedDevices())
    override val devices: StateFlow<List<Device>> = _devices.asStateFlow()

    private val _activities = MutableStateFlow(seedActivities())
    override val activities: StateFlow<List<ActivityEvent>> = _activities.asStateFlow()

    override fun device(id: String): Device? = _devices.value.firstOrNull { it.id == id }

    override fun roomDevices(roomId: String): List<Device> =
        _devices.value.filter { it.roomId == roomId }

    override fun updateDevice(id: String, transform: (DeviceState) -> DeviceState) {
        _devices.update { list ->
            list.map { d -> if (d.id == id) d.copy(state = transform(d.state)) else d }
        }
    }

    private fun seedRooms(): List<Room> = listOf(
        Room("doorbell",     "Doorbell",     listOf("doorbell_1")),
        Room("living_room",  "Living room",  listOf("lamp_living", "thermo_living", "lock_front")),
        Room("kitchen",      "Kitchen",      listOf("leak_kitchen", "smoke_kitchen", "vacuum_1")),
        Room("backyard",     "Backyard",     emptyList()),
        Room("bedroom",      "Bedroom",      listOf("lamp_bedroom", "thermo_bedroom", "curtains_bedroom")),
    )

    private fun seedDevices(): List<Device> = listOf(
        Device("doorbell_1", "Doorbell",
            roomId = "doorbell",
            state = DeviceState.Doorbell(online = true, streamingLive = true),
        ),
        Device("lock_front", "Smart door lock",
            roomId = "living_room",
            state = DeviceState.Lock(locked = true, battery = 99),
        ),
        Device("thermo_living", "Thermostat",
            roomId = "living_room",
            state = DeviceState.Thermostat(
                targetC = 22f, currentC = 22f, outsideC = 17f,
                humidity = 0.78f, heating = true, cooling = false,
            ),
        ),
        Device("vacuum_1", "Smart vacuum cleaner",
            roomId = "kitchen",
            state = DeviceState.Vacuum(running = true, minutesLeft = 23, battery = 19),
        ),
        Device("leak_kitchen", "Water leak detector",
            roomId = "kitchen",
            state = DeviceState.LeakDetector(leaking = false, battery = 100),
        ),
        Device("smoke_kitchen", "Smoke detector",
            roomId = "kitchen",
            state = DeviceState.SmokeDetector(smoke = false, battery = 100),
        ),
        Device("lamp_living", "Living room lamp",
            roomId = "living_room",
            state = DeviceState.Light(on = true, brightness = 0.7f, colorHex = 0xFFFFD27AL, timerOn = false),
        ),
        Device("lamp_bedroom", "Main light",
            roomId = "bedroom",
            state = DeviceState.Light(on = true, brightness = 0.55f, colorHex = 0xFFFFD27AL, timerOn = false),
        ),
        Device("thermo_bedroom", "Thermostat",
            roomId = "bedroom",
            state = DeviceState.Thermostat(
                targetC = 22f, currentC = 22f, outsideC = 17f,
                humidity = 0.78f, heating = true, cooling = false,
            ),
        ),
        Device("curtains_bedroom", "Curtains",
            roomId = "bedroom",
            state = DeviceState.Curtains(position = CurtainPosition.Half, brightness = 0.6f, auto = false),
        ),
    )

    private fun seedActivities(): List<ActivityEvent> = listOf(
        ActivityEvent(
            id = "ev_1",
            kinds = listOf(ActivityKind.Sound, ActivityKind.Animal, ActivityKind.Motion),
            title = "Sound, Animal detected, Motion",
            startedAt = "11:12:43",
            endedAt = "11:21:12",
            thumbnailUrl = null,
            live = true,
        ),
        ActivityEvent(
            id = "ev_2",
            kinds = listOf(ActivityKind.Animal),
            title = "Animal detected",
            startedAt = "09:50:43",
            endedAt = "12:43",
            thumbnailUrl = null,
            live = false,
        ),
        ActivityEvent(
            id = "ev_3",
            kinds = listOf(ActivityKind.Package),
            title = "Package delivered",
            startedAt = "08:02:11",
            endedAt = "08:02:55",
            thumbnailUrl = null,
            live = false,
        ),
    )
}

